<?php

/**
 * Implements hook_commerce_checkout_pane_info()
 */
function ac_comment_commerce_checkout_pane_info() {
  $panes = array();

  $panes['adapt_commerce_comment'] = array(
    'title' => t(variable_get('ac_comment_panel_title', 'Leave a comment')),
    'base' => 'ac_comment',
    'page' => 'checkout',
    'file' => 'includes/comment.checkout_pane.inc',
    'review' => true,
  );

  return $panes;
}

/**
 * Implements hook_theme().
 */
function ac_comment_theme($existing, $type, $theme, $path) {
  return array(
    'ac_comment_token_view' => array(
      'template' => 'ac-comment-token-view',
      'variables' => array(
        'comment' => '',
        'content' => '',
      ),
      'path' => $path . '/tpl',
    ),
  );
}

/**
 * Preprocess function for contact information.
 */
function ac_comment_preprocess_ac_comment_token_view(&$variables) {
  $comment = $variables['comment'];
  $header = array(
    t('Comment'),
  );
  $rows = array(0 => array($comment));
  $attributes = array(
    'class' => array('contact-info'),
  );
  $table = theme(
    'table',
    array(
      'header' => $header,
      'rows' => $rows,
      'attributes' => $attributes,
    )
  );
  $variables['content'] = $table;
}
