<?php

/**
 * @file ac_mailchimp_extension.module
 * Code to implement module functionallity.
 */

/**
 * Implements hook_commerce_checkout_pane_info()
 */
function ac_mailchimp_extension_commerce_checkout_pane_info() {
  $panes = array();

  $panes['adapt_commerce_mailchimp_extension'] = array(
    'title' => t(variable_get('ac_mailchimp_extension_panel_title', 'Subscribe to be updated?')),
    'base' => 'ac_mailchimp_extension',
    'page' => 'review',
    'file' => 'includes/mailchimp_extension.checkout_pane.inc',
  );

  return $panes;
}
